<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="cerlab_mecanum">

    <!-- Bring robot parts to the model -->
    <xacro:include filename="$(find cerlab_mecanum)/urdf/robot_parts/mecanum_wheel.xacro"    />
    <xacro:include filename="$(find cerlab_mecanum)/urdf/robot_parts/base_link.xacro"        />
    <xacro:include filename="$(find cerlab_mecanum)/urdf/robot_parts/lidar.xacro"            />
    <xacro:include filename="$(find cerlab_mecanum)/urdf/robot_parts/imu.xacro"              />
    <xacro:include filename="$(find cerlab_mecanum)/urdf/robot_parts/emergency_button.xacro" />
    <xacro:include filename="$(find cerlab_mecanum)/urdf/robot_parts/fan.xacro"              />

    <xacro:property name="PI" value="3.1415926535897931" />

    <!-- Robot body ( base link ) parameters -->
    <xacro:property name="base_link_length" value="0.461"/>
    <xacro:property name="base_link_width"  value="0.580"/>
    <xacro:property name="base_link_height" value="0.152"/>

    <!-- Wheel parameters -->
    <xacro:property name="wheel_radius" value="${0.203/2}"/>
    <xacro:property name="wheel_width"  value="0.078"     />


    <xacro:include filename="$(find cerlab_mecanum)/urdf/robot.gazebo"/>
    

    <link name="base_footprint"></link>


    <!-- Adding the main body -->

    <xacro:base_link parent="base_footprint">
        <origin xyz="0 0 ${wheel_radius + base_link_height/2}" rpy="0 0 0" />
    </xacro:base_link>

    <xacro:base_plate_link parent="base_footprint" length="${base_link_length}" width="${base_link_width - 0.032}" height="0.001">
        <origin xyz="0 0.023 ${wheel_radius + 0.02}" rpy="0 0 0" />
    </xacro:base_plate_link>


    <!-- Adding mecanum wheels -->

    <xacro:omni_wheel prefix="xpyp" parent="base_link" reflect="false">
        <origin xyz="${base_link_length/2 + wheel_width/2 + 0.01} ${base_link_width/2-0.065} ${-base_link_height/2 + 0.02}" rpy="0 0 ${PI/2}"/>
    </xacro:omni_wheel>

    <xacro:omni_wheel prefix="xnyp" parent="base_link" reflect="true">
        <origin xyz="${-base_link_length/2 - wheel_width/2 - 0.01} ${base_link_width/2-0.065} ${-base_link_height/2 + 0.02}" rpy="0 0 ${PI/2}"/>
    </xacro:omni_wheel>

    <xacro:omni_wheel prefix="xpyn" parent="base_link" reflect="true">
        <origin xyz="${base_link_length/2 + wheel_width/2 + 0.01} ${-base_link_width/2+0.095} ${-base_link_height/2 + 0.02}" rpy="0 0 ${PI/2}"/>
    </xacro:omni_wheel>

    <xacro:omni_wheel prefix="xnyn" parent="base_link" reflect="false">
        <origin xyz="${-base_link_length/2 - wheel_width/2 - 0.01} ${-base_link_width/2+0.095} ${-base_link_height/2 + 0.02}" rpy="0 0 ${PI/2}"/>
    </xacro:omni_wheel>


    <!-- Adding LiDAR sensors -->

    <xacro:lidar prefix="front" parent="base_link">
        <origin xyz="0 ${base_link_width/2-0.046} ${base_link_height/2+0.05}" rpy="0 0 0"/>
    </xacro:lidar>

    <xacro:lidar prefix="back" parent="base_link">
        <origin xyz="0 ${-base_link_width/2+0.1} ${base_link_height/2+0.05}" rpy="0 0 0"/>
    </xacro:lidar>

    <!-- Adding the Inertial Measurement Unit (IMU) -->
    <xacro:imu/>


    <!-- Adding the emergency buttons (visual feedback only) -->

    <xacro:emergency_button prefix="front" parent="base_link">
        <origin xyz="0 ${base_link_width/2+0.017} 0" rpy="${-PI/2} 0 0"/>
    </xacro:emergency_button>

    <xacro:emergency_button prefix="back" parent="base_link">
        <origin xyz="0 ${-base_link_width/2+0.03} 0" rpy="${PI/2} 0 0"/>
    </xacro:emergency_button>


    <!-- Adding power button (visual feedback only) -->
    <joint name="power_button_joint" type="fixed">
        <parent link="base_link"/>
        <child link="power_button_link"/>
        <origin xyz="0 ${-base_link_width/2+0.047} 0.0415" rpy="${PI/2} 0 0"/>
    </joint>

        <link name="power_button_link">
            <visual>
                <origin rpy=" 0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="package://cerlab_mecanum/meshes/power_button.stl" scale="0.0011 0.0011 0.0011"/>
                </geometry>
            </visual>
            <collision>
                <origin rpy=" 0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="package://cerlab_mecanum/meshes/power_button.stl" scale="0.0011 0.0011 0.0011"/>
                </geometry>
            </collision>
        </link>

        <gazebo reference="power_button_link">
            <material>Gazebo/Black</material>
        </gazebo>
    
    <!-- Adding fans (visual feedback only) -->

    <xacro:fan prefix="left" parent="base_link">
        <origin xyz="-0.08 ${-base_link_width/2+0.055} ${0.0415/2+0.01}" rpy="${PI/2} 0 0"/>
    </xacro:fan>

    <xacro:fan prefix="right" parent="base_link">
        <origin xyz="0.08 ${-base_link_width/2+0.055} ${0.0415/2+0.01}0" rpy="${PI/2} 0 0"/>
    </xacro:fan>

</robot>